apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJ1Z2dlMHV6
  CLOUDINARY_KEY: MjM0Mjk1MTY1NjY1MTE2
  CLOUDINARY_SECRET: N3kyeGZaSWRWSlBoTXM0THpYeW14NVVyaUpJ
  MAPBOX_TOKEN: cGsuZXlKMUlqb2liV0Z1YVd0aGJuUm9NallpTENKaElqb2lZMjF0ZURWbGFHWnRNRFp2T0RKd2NYUnRaR1JtZERrMGNDSjkuMlJyTFA1WmZodjVtOUNuZEZjSkowUQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyM0BjbHVzdGVyMC5iYTk1bmh2Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw

